# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patid', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('keyterm', models.TextField(blank=True, null=True)),
                ('freq', models.FloatField(blank=True, null=True)),
                ('path', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'docs',
            },
        ),
    ]
